DATALOADER:
  TRAIN:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 64
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 20
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5

MODEL:
  NAME: Dorset
  Dorset:
    TUNING: False
    ALPHA: 6.06
    BETA: 0.39
    GAMMA: 0.2
    LAMBDA: 0.7
    SEARCH_SCALE: [15, 3, 0.5]
    SEARCH_STEP: [50, 30, 10]
    NUM_FEATURES: 256
    BACKBONE: "ViT-B/32"
    K: 5